### 获取所有服务实例
GET http://localhost:8484/findAll?service=com.lcl.lclrpc.demo.api.UserService

### 注册一个服务实例
POST http://localhost:8484/reg?service=com.lcl.lclrpc.demo.api.UserService
Content-Type: application/json

{
  "schema": "http",
  "host": "127.0.0.1",
  "port": 8081,
  "context": "lclrpc",
  "parameters": {
    "env": "dev",
    "tag": "RED"
  },
  "status": false
}


###
POST http://localhost:8484/unreg?service=com.lcl.lclrpc.demo.api.UserService
Content-Type: application/json

{
  "schema": "http",
  "host": "127.0.0.1",
  "port": 8082,
  "context": "lclrpc"
}